# Analysis code for 'Communication increases category structure and alignment only when combined with cultural transmission'

# reproduces graphs and statistical analyses reported in the paper

# uses as input the files generated by the associated Python code in data.py and analysis_scripts.py

# get required packages
required_packages <- c("ggplot2", "psych")

new_packages <- required_packages[!(required_packages %in% installed.packages()[,"Package"])]
if(length(new_packages)) install.packages(new_packages)

# load
library(psych)
library(ggplot2)

# function for calculating confidence intervals

conf_ints_within <- function(mean, df, se) {
  tval <- qt(.975,df)
  lowlim = mean - (se * tval)
  uplim = mean + (se * tval)
  conf_int <- list("Mean" = mean, "Lowlim" = lowlim, "Uplim" = uplim)
  return(conf_int)
}

# function for calculating confidence interval on between-group difference

conf_ints_between <- function(m1, m2, sd1, sd2, n1, n2, method) {
  mean_diff = abs(m1-m2)
  if (method == "WS") {
    se <- sqrt((sd1^2/n1)+(sd2^2/n2))
    df <- ((sd1^2/n1+sd2^2/n2)^2)/((sd1^4/(n1^2*(n1-1)))+(sd2^4/(n2^2*(n2-1))))
    tval <- qt(.975,df)
    MOE <- tval*se
  } else {
    sp = sqrt(((n1-1)*sd1^2 + (n2-1)*sd2^2)/(n1+n2-2))
    tval <- qt(.975,n1+n2-2)
    MOE = tval * sp * sqrt(1/n1 + 1/n2)
  }
  lowlim <- mean_diff - MOE
  uplim <- mean_diff + MOE
  conf_int <- list("Mean" = mean_diff, "Lowlim" = lowlim, "Uplim" = uplim)
  return(conf_int)
}

# function for calculating confidence intervals on SDs
# from Sheskin (2011), p.77-78

conf_ints_sd <- function(sd, n) {
  var = sd^2
  lowlim = sqrt((n-1)*var/qchisq(0.975, df=(n-1)))
  uplim = sqrt((n-1)*var/qchisq(0.025, df=(n-1)))
  conf_int <- list("SD" = sd, "Lowlim" = lowlim, "Uplim" = uplim)
  return(conf_int)
}

# function for calculating confidence intervals on r
# from Cumming (2012)

conf_ints_r <- function(r, n) {
  zr = 0.5 * log(((1+r)/(1-r)),base=exp(1))
  # get lowlim & uplim in zr
  zlowlim = zr-1.96*1/(sqrt(n-3))
  zuplim = zr+1.96*1/(sqrt(n-3))
  # convert these back to r units
  lowlim = (exp(1)^(2*zlowlim)-1)/(exp(1)^(2*zlowlim)+1)
  uplim = (exp(1)^(2*zuplim)-1)/(exp(1)^(2*zuplim)+1)
  conf_int <- list("r" = r, "Lowlim" = lowlim, "Uplim" = uplim)
  return(conf_int)
}


# Experiment 1

# for specificity and convexity, degrees of freedom are 20-1 = 19 for individual, and 10-1 = 9 for communicative
idf = 19
cdf = 9

# Specificity

# read in data

# if not running RStudio, manually set working directory to location of script (folder containing output folder)
WORKING_DIR <- ""
if (rstudioapi::isAvailable()) {
  setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
} else {
    if (WORKING_DIR == "") {
        stop("Please either use RStudio to run this script, or manually specify the working\
        directory in variable WORKING_DIR above.")
    } else {
        setwd(WORKING_DIR)
    }
}

exp1spec <- read.delim("output/experiment_1_specificity.txt", header = TRUE, sep = "\t")

indiv <- subset(exp1spec, Condition == "i")
comm <- subset(exp1spec, Condition == "c")

# average communicative pairs

comm_avs <- by(comm$Specificity, gl(ceiling(length(comm$Specificity)/2), 2, length(comm$Specificity)), mean)
comm_avs <- as.list(comm_avs)
comm_avs <- data.frame(Specificity = do.call("rbind", comm_avs))

exp1spec <- rbind(indiv, data.frame(Condition = "c", Specificity = comm_avs$Specificity))

# reorder factor levels

exp1spec$Condition = factor(exp1spec$Condition,levels(exp1spec$Condition)[c(2,1)])

# Confidence intervals

exp1_spec_descriptives <- describeBy(exp1spec$Specificity, exp1spec$Condition, mat = TRUE)

# reorder factor levels

exp1_spec_descriptives$group1 = factor(exp1_spec_descriptives$group1,levels(exp1_spec_descriptives$group1)[c(2,1)])

# add confidence intervals

exp1_spec_i_ci <- conf_ints_within(exp1_spec_descriptives[1, 5], idf, exp1_spec_descriptives[1, 15])
exp1_spec_c_ci <- conf_ints_within(exp1_spec_descriptives[2, 5], cdf, exp1_spec_descriptives[2, 15])

print(exp1_spec_i_ci)
print(exp1_spec_c_ci)

exp1_spec_descriptives["Lowlim"] <- c(exp1_spec_i_ci$Lowlim, exp1_spec_c_ci$Lowlim)
exp1_spec_descriptives["Uplim"] <- c(exp1_spec_i_ci$Uplim, exp1_spec_c_ci$Uplim)

# between group confidence intervals - use Welch-Satterthwaite method because of unequal variances

exp1_spec_between_ci <- conf_ints_between(m1 = exp1_spec_descriptives[1,5], m2 = exp1_spec_descriptives[2,5], sd1 = exp1_spec_descriptives[1,6],
                  sd2 = exp1_spec_descriptives[2,6], n1 = exp1_spec_descriptives[1,4], n2 = exp1_spec_descriptives[2,4],
                  method = "WS")

print(exp1_spec_between_ci)

# confidence intervals on SDs

exp1_spec_i_sd_ci <- conf_ints_sd(exp1_spec_descriptives[1,6], exp1_spec_descriptives[1,4])

print(exp1_spec_i_sd_ci)

exp1_spec_c_sd_ci <- conf_ints_sd(exp1_spec_descriptives[2,6], exp1_spec_descriptives[2,4])

print(exp1_spec_c_sd_ci)

# Graph

# parameters to be used in this and all subsequent plots
xaxistitle <- element_text(vjust=-0.5,size=14,face="bold")
yaxistitle <- element_text(vjust=0.2,size=14,face="bold")
axistext <- element_text(size=12)

exp1_spec_graph <- ggplot(exp1spec, aes(x = Condition, y = Specificity))
exp1_spec_graph + theme_bw() + geom_dotplot(binaxis = "y", stackdir = "center", binpositions = "all", fill = "grey80", color = "grey80") +
  scale_x_discrete("\nCondition", labels=c("Individual","Communication")) + 
  scale_y_continuous('Specificity\n', limits = c(0, 17)) + 
  theme(axis.text=axistext,axis.title.x=xaxistitle, axis.title.y=yaxistitle, legend.position="None") +
  geom_point(data = exp1_spec_descriptives, aes(x = group1, y = mean), size = 2) +
  geom_errorbar(data = exp1_spec_descriptives, aes(x = group1, y = mean, ymin = Lowlim, ymax = Uplim), width = 0.25, size = 1)
ggsave(filename="Exp1Specificity.pdf",width=7.25,height=5.5)

# Statistical analysis

exp1_spec_stat <- t.test(Specificity ~ Condition, exp1spec)
print(exp1_spec_stat)


# Convexity

# read in data

exp1conv <- read.delim("output/experiment_1_convexity.txt", header = TRUE, sep = "\t")

indiv <- subset(exp1conv, Condition == "i")[c(1, 5)]
comm <- subset(exp1conv, Condition == "c")[c(1, 5)]

# average communicative pairs

comm_avs <- by(comm$Corrected, gl(ceiling(length(comm$Corrected)/2), 2, length(comm$Corrected)), mean)
comm_avs <- as.list(comm_avs)
comm_avs <- data.frame(Corrected = do.call("rbind", comm_avs))

exp1conv <- rbind(indiv, data.frame(Condition = "c", Corrected = comm_avs$Corrected))

# reorder factor levels

exp1conv$Condition = factor(exp1conv$Condition,levels(exp1conv$Condition)[c(2,1)])

# Confidence intervals

exp1_conv_descriptives <- describeBy(exp1conv$Corrected, exp1conv$Condition, mat = TRUE)

# reorder factor levels

exp1_conv_descriptives$group1 = factor(exp1_conv_descriptives$group1,levels(exp1_conv_descriptives$group1)[c(2,1)])

# add confidence intervals

exp1_conv_i_ci <- conf_ints_within(exp1_conv_descriptives[1, 5], idf, exp1_conv_descriptives[1, 15])
exp1_conv_c_ci <- conf_ints_within(exp1_conv_descriptives[2, 5], cdf, exp1_conv_descriptives[2, 15])

print(exp1_conv_i_ci)
print(exp1_conv_c_ci)

exp1_conv_descriptives["Lowlim"] <- c(exp1_conv_i_ci$Lowlim, exp1_conv_c_ci$Lowlim)
exp1_conv_descriptives["Uplim"] <- c(exp1_conv_i_ci$Uplim, exp1_conv_c_ci$Uplim)

# between group confidence intervals - use Welch-Satterthwaite method because of unequal variances

exp1_conv_between_ci <- conf_ints_between(m1 = exp1_conv_descriptives[1,5], m2 = exp1_conv_descriptives[2,5], sd1 = exp1_conv_descriptives[1,6],
                                          sd2 = exp1_conv_descriptives[2,6], n1 = exp1_conv_descriptives[1,4], n2 = exp1_conv_descriptives[2,4],
                                          method = "WS")

print(exp1_conv_between_ci)

# confidence intervals on SDs

exp1_conv_i_sd_ci <- conf_ints_sd(exp1_conv_descriptives[1,6], exp1_conv_descriptives[1,4])

print(exp1_conv_i_sd_ci)

exp1_conv_c_sd_ci <- conf_ints_sd(exp1_conv_descriptives[2,6], exp1_conv_descriptives[2,4])

print(exp1_conv_c_sd_ci)

# Graph

exp1_conv_graph <- ggplot(exp1conv, aes(x = Condition, y = Corrected))
exp1_conv_graph + theme_bw() + geom_dotplot(binaxis = "y", stackdir = "center", binpositions = "all", fill = "grey80", color = "grey80") +
  scale_x_discrete("\nCondition", labels=c("Individual","Communication")) + 
  scale_y_continuous('Convexity\n', limits = c(0, 1)) + 
  theme(axis.text=axistext,axis.title.x=xaxistitle, axis.title.y=yaxistitle, legend.position="None") +
  geom_point(data = exp1_conv_descriptives, aes(x = group1, y = mean), size = 2) +
  geom_errorbar(data = exp1_conv_descriptives, aes(x = group1, y = mean, ymin = Lowlim, ymax = Uplim), width = 0.25, size = 1)
ggsave(filename="Exp1Convexity.pdf",width=7.25,height=5.5)


# Statistical analysis

exp1_conv_stat <- t.test(Corrected ~ Condition, exp1conv)
print(exp1_conv_stat)


# Alignment and convergence

# for alignment, degrees of freedom are 10-1 = 9 for both conditions
idf = 9
cdf = 9

# read in data

exp1align <- read.delim("output/experiment_1_alignment.txt", header = TRUE, sep = "\t")

# reorder factor levels

exp1align$Condition = factor(exp1align$Condition,levels(exp1align$Condition)[c(2,1)])

# Confidence intervals

exp1_align_descriptives <- describeBy(exp1align$AdjustedRandIndex, exp1align$Condition, mat = TRUE)

# reorder factor levels

exp1_align_descriptives$group1 = factor(exp1_align_descriptives$group1,levels(exp1_align_descriptives$group1)[c(2,1)])

# add confidence intervals

exp1_align_i_ci <- conf_ints_within(exp1_align_descriptives[1, 5], idf, exp1_align_descriptives[1, 15])
exp1_align_c_ci <- conf_ints_within(exp1_align_descriptives[2, 5], cdf, exp1_align_descriptives[2, 15])

print(exp1_align_i_ci)
print(exp1_align_c_ci)

exp1_align_descriptives["Lowlim"] <- c(exp1_align_i_ci$Lowlim, exp1_align_c_ci$Lowlim)
exp1_align_descriptives["Uplim"] <- c(exp1_align_i_ci$Uplim, exp1_align_c_ci$Uplim)

# between group confidence intervals - use Welch-Satterthwaite method because of unequal variances

exp1_align_between_ci <- conf_ints_between(m1 = exp1_align_descriptives[1,5], m2 = exp1_align_descriptives[2,5], sd1 = exp1_align_descriptives[1,6],
                                          sd2 = exp1_align_descriptives[2,6], n1 = exp1_align_descriptives[1,4], n2 = exp1_align_descriptives[2,4],
                                          method = "WS")

print(exp1_align_between_ci)

# confidence intervals on SDs

exp1_align_i_sd_ci <- conf_ints_sd(exp1_align_descriptives[1,6], exp1_align_descriptives[1,4])

print(exp1_align_i_sd_ci)

exp1_align_c_sd_ci <- conf_ints_sd(exp1_align_descriptives[2,6], exp1_align_descriptives[2,4])

print(exp1_align_c_sd_ci)

# Graph - alignment

exp1_align_graph <- ggplot(exp1align, aes(x = Condition, y = AdjustedRandIndex))
exp1_align_graph + theme_bw() + geom_dotplot(binaxis = "y", stackdir = "center", binpositions = "all", fill = "grey80", color = "grey80") +
  scale_x_discrete("\nCondition", labels=c("Individual","Communication")) + 
  scale_y_continuous('Alignment (Adjusted Rand index)\n', limits = c(-0.05, 1)) + 
  theme(axis.text=axistext,axis.title.x=xaxistitle, axis.title.y=yaxistitle, legend.position="None") +
  geom_point(data = exp1_align_descriptives, aes(x = group1, y = mean), size = 2) +
  geom_errorbar(data = exp1_align_descriptives, aes(x = group1, y = mean, ymin = Lowlim, ymax = Uplim), width = 0.25, size = 1)
ggsave(filename="Exp1Alignment.pdf",width=7.25,height=5.5)

# Statistical analysis

exp1_align_stat <- t.test(AdjustedRandIndex ~ Condition, exp1align)
print(exp1_align_stat)


# Convergence

# Here, confidence intervals are calculated via a Monte Carlo process in the Python code

# read in data

exp1converge <- read.delim("output/experiment_1_convergence.txt", header = TRUE, sep = "\t")

print(exp1converge)

# reorder factor levels

exp1converge$Condition = factor(exp1converge$Condition,levels(exp1converge$Condition)[c(2,1)])

exp1_converge_graph <- ggplot(exp1converge, aes(x=Condition, y=Convergence))
exp1_converge_graph + theme_bw() + geom_point(size = 2) + geom_errorbar(aes(ymin=LowLim, ymax=UpLim), width=.25, size = 1) + scale_x_discrete("\nCondition", labels=c("Individual","Communication")) + scale_y_continuous('',limits=c(0,1.0)) + theme(axis.text = axistext, axis.title.x=xaxistitle, axis.title.y=yaxistitle, legend.position = "none")
ggsave(filename="Exp1Convergence.pdf",width=7.25,height=5.5)


# Communicative success

# read in data

exp1success_by_round <- read.delim("output/experiment_1_success_by_round.txt", header = TRUE, sep = "\t")

# confidence intervals

exp1_success_by_round_descriptives <- describeBy(exp1success_by_round$Score, exp1success_by_round$Round, mat = TRUE)

exp1_success_by_round_1_ci <- conf_ints_within(exp1_success_by_round_descriptives[1, 5], idf, exp1_success_by_round_descriptives[1, 15])
exp1_success_by_round_4_ci <- conf_ints_within(exp1_success_by_round_descriptives[4, 5], cdf, exp1_success_by_round_descriptives[4, 15])

print(exp1_success_by_round_1_ci)
print(exp1_success_by_round_4_ci)


# between group confidence intervals - use Welch-Satterthwaite method because of unequal variances

exp1_success_by_round_between_ci <- conf_ints_between(m1 = exp1_success_by_round_descriptives[1,5], m2 = exp1_success_by_round_descriptives[4,5], sd1 = exp1_success_by_round_descriptives[1,6],
                                           sd2 = exp1_success_by_round_descriptives[4,6], n1 = exp1_success_by_round_descriptives[1,4], n2 = exp1_success_by_round_descriptives[4,4],
                                           method = "WS")

print(exp1_success_by_round_between_ci)


# correlation between success in last 2 rounds and specificity

# read in data

exp1success <- read.delim("output/experiment_1_success_last_2.txt", header = TRUE, sep = "\t")

exp1spec_comm_only <- subset(exp1spec, Condition == "c")

exp1_success_spec <- cbind(exp1success, exp1spec_comm_only)

exp1_success_spec_corr <- cor.test(exp1_success_spec$Specificity, exp1_success_spec$Success)

print(exp1_success_spec_corr)

exp1_success_spec_corr_confint <- conf_ints_r(r = exp1_success_spec_corr$estimate, 10)

print(exp1_success_spec_corr_confint)

# correlation between success in last 2 rounds and alignment

exp1align_comm_only <- subset(exp1align, Condition == "c")

exp1_success_align <- cbind(exp1success, exp1align_comm_only)

exp1_success_align_corr <- cor.test(exp1_success_align$AdjustedRandIndex, exp1_success_align$Success)

print(exp1_success_align_corr)

exp1_success_align_corr_confint <- conf_ints_r(r = exp1_success_align_corr$estimate, 10)

print(exp1_success_align_corr_confint)


# Experiment 2

# Comparison of training scores (adjusted for language difficulty) between two conditions

# read in data

exp2train <- read.delim("output/experiment_2_training_scores.txt", header = TRUE, sep = "\t")

# correct scores according to how many categories were to be learned

exp2train["CorrectedScore"] <- exp2train$NumCats * exp2train$Score

# scores are ordinal so we use a Wilcoxon test

exp2_train_stat <- wilcox.test(CorrectedScore ~ Condition, exp2train)

print(exp2_train_stat)

# for specificity and convexity, degrees of freedom are 16-1 = 15 for transmission-alone, and 8-1 = 7 for transmission + communication
idf = 15
cdf = 7

# Specificity

# read in data

exp2spec <- read.delim("output/experiment_2_specificity.txt", header = TRUE, sep = "\t")

tmiss <- subset(exp2spec, Condition == "t")
comm <- subset(exp2spec, Condition == "c")

# average communicative pairs
# make vector of Generation to add back
gen_vector = rep(c(1, 2, 3, 4, 5), 8)

comm_avs <- by(comm$Specificity, gl(ceiling(length(comm$Specificity)/2), 2, length(comm$Specificity)), mean)
comm_avs <- as.list(comm_avs)
comm_avs <- data.frame(Specificity = do.call("rbind", comm_avs))

exp2spec <- rbind(tmiss, data.frame(Condition = "c", Generation = gen_vector, Specificity = comm_avs$Specificity))

# reorder factor levels

exp2spec$Condition = factor(exp2spec$Condition,levels(exp2spec$Condition)[c(2,1)])

# Confidence intervals

exp2_spec_descriptives <- describeBy(exp2spec$Specificity, list(exp2spec$Condition, exp2spec$Generation), mat = TRUE)

# reorder factor levels

exp2_spec_descriptives$group1 = factor(exp2_spec_descriptives$group1,levels(exp2_spec_descriptives$group1)[c(2,1)])

# add confidence intervals

exp2_spec_t_g1_ci <- conf_ints_within(exp2_spec_descriptives[1, 6], idf, exp2_spec_descriptives[1, 16])
exp2_spec_c_g1_ci <- conf_ints_within(exp2_spec_descriptives[2, 6], cdf, exp2_spec_descriptives[2, 16])

print(exp2_spec_t_g1_ci)
print(exp2_spec_c_g1_ci)

# between conditions in generation 1

exp2_spec_g1_between_ci <- conf_ints_between(m1 = exp2_spec_descriptives[1,6], m2 = exp2_spec_descriptives[2,6], sd1 = exp2_spec_descriptives[1,7],
                                          sd2 = exp2_spec_descriptives[2,7], n1 = exp2_spec_descriptives[1,5], n2 = exp2_spec_descriptives[2,5],
                                          method = "WS")

print(exp2_spec_g1_between_ci)

# calculate rest of confidence intervals

exp2_spec_t_g2_ci <- conf_ints_within(exp2_spec_descriptives[3, 6], idf, exp2_spec_descriptives[3, 16])
exp2_spec_c_g2_ci <- conf_ints_within(exp2_spec_descriptives[4, 6], idf, exp2_spec_descriptives[4, 16])
exp2_spec_t_g3_ci <- conf_ints_within(exp2_spec_descriptives[5, 6], idf, exp2_spec_descriptives[5, 16])
exp2_spec_c_g3_ci <- conf_ints_within(exp2_spec_descriptives[6, 6], idf, exp2_spec_descriptives[6, 16])
exp2_spec_t_g4_ci <- conf_ints_within(exp2_spec_descriptives[7, 6], idf, exp2_spec_descriptives[7, 16])
exp2_spec_c_g4_ci <- conf_ints_within(exp2_spec_descriptives[8, 6], idf, exp2_spec_descriptives[8, 16])

# generation 5

exp2_spec_t_g5_ci <- conf_ints_within(exp2_spec_descriptives[9, 6], idf, exp2_spec_descriptives[9, 16])
exp2_spec_c_g5_ci <- conf_ints_within(exp2_spec_descriptives[10, 6], cdf, exp2_spec_descriptives[10, 16])

print(exp2_spec_t_g5_ci)
print(exp2_spec_c_g5_ci)

# difference from generation 1 to 5 in transmission condition

exp2_spec_t_between_ci <- conf_ints_between(m1 = exp2_spec_descriptives[1,6], m2 = exp2_spec_descriptives[9,6], sd1 = exp2_spec_descriptives[1,7],
                                            sd2 = exp2_spec_descriptives[9,7], n1 = exp2_spec_descriptives[1,5], n2 = exp2_spec_descriptives[9,5],
                                            method = "standard")

print(exp2_spec_t_between_ci)

# difference from generation 1 to 5 in communication condition

exp2_spec_c_between_ci <- conf_ints_between(m1 = exp2_spec_descriptives[2,6], m2 = exp2_spec_descriptives[10,6], sd1 = exp2_spec_descriptives[2,7],
                                            sd2 = exp2_spec_descriptives[10,7], n1 = exp2_spec_descriptives[2,5], n2 = exp2_spec_descriptives[10,5],
                                            method = "WS")

print(exp2_spec_c_between_ci)

# comparison of final number in transmission condition in experiment 2 with individuals from experiment 1

exp2_spec_c_between_expts_ci_1 <- conf_ints_between(m1 = exp1_spec_descriptives[1,5], m2 = exp2_spec_descriptives[9,6], sd1 = exp1_spec_descriptives[1,6],
                                            sd2 = exp2_spec_descriptives[9,7], n1 = exp1_spec_descriptives[1,4], n2 = exp2_spec_descriptives[9,5],
                                            method = "WS")

print(exp2_spec_c_between_expts_ci_1)

# comparison of final number in communication condition in experiment 2 with communicators from experiment 1

exp2_spec_c_between_expts_ci_2 <- conf_ints_between(m1 = exp1_spec_descriptives[2,5], m2 = exp2_spec_descriptives[10,6], sd1 = exp1_spec_descriptives[2,6],
                                                  sd2 = exp2_spec_descriptives[10,7], n1 = exp1_spec_descriptives[2,4], n2 = exp2_spec_descriptives[10,5],
                                                  method = "WS")

print(exp2_spec_c_between_expts_ci_2)

# add all these to data frame

exp2_spec_descriptives["Lowlim"] <- c(exp2_spec_t_g1_ci$Lowlim, exp2_spec_c_g1_ci$Lowlim, 
                                      exp2_spec_t_g2_ci$Lowlim, exp2_spec_c_g2_ci$Lowlim, 
                                      exp2_spec_t_g3_ci$Lowlim, exp2_spec_c_g3_ci$Lowlim, 
                                      exp2_spec_t_g4_ci$Lowlim, exp2_spec_c_g4_ci$Lowlim, 
                                      exp2_spec_t_g5_ci$Lowlim, exp2_spec_c_g5_ci$Lowlim)
exp2_spec_descriptives["Uplim"] <- c(exp2_spec_t_g1_ci$Uplim, exp2_spec_c_g1_ci$Uplim, 
                                     exp2_spec_t_g2_ci$Uplim, exp2_spec_c_g2_ci$Uplim, 
                                     exp2_spec_t_g3_ci$Uplim, exp2_spec_c_g3_ci$Uplim, 
                                     exp2_spec_t_g4_ci$Uplim, exp2_spec_c_g4_ci$Uplim, 
                                     exp2_spec_t_g5_ci$Uplim, exp2_spec_c_g5_ci$Uplim)



# Graph

# average transmission pairs as well for clarity

comm <- subset(exp2spec, Condition == "c")
tmiss <- subset(exp2spec, Condition == "t")

tmiss_avs <- by(tmiss$Specificity, gl(ceiling(length(tmiss$Specificity)/2), 2, length(tmiss$Specificity)), mean)
tmiss_avs <- as.list(tmiss_avs)
tmiss_avs <- data.frame(Specificity = do.call("rbind", tmiss_avs))

exp2spec_plot <- rbind(data.frame(Condition = "t", Generation = gen_vector, Specificity = tmiss_avs$Specificity), comm)


# add Chain back to data frame for grouping raw data

chain_vector <- c(rep(1,5), rep(2,5), rep(3,5), rep(4,5), rep(5,5), rep(6,5), rep(7,5), rep(8,5),
                  rep(1,5), rep(2,5), rep(3,5), rep(4,5), rep(5,5), rep(6,5), rep(7,5), rep(8,5))

exp2spec_plot$Chain <- chain_vector

# for dodging errorbars - to be used here and in all following plots
dodge <- position_dodge(width=0.25)

exp2_spec_graph <- ggplot(exp2spec_plot, aes(x=Generation, y=Specificity))
exp2_spec_graph + theme_bw() + geom_line(aes(linetype = Condition, color = Condition, group=interaction(Chain, Condition)), alpha = 0.3, show.legend = FALSE) + 
  scale_x_discrete("\nGeneration") + scale_y_continuous('Specificity\n', limits=c(0,22)) + 
  scale_linetype_discrete("Condition",breaks=c("t","c"),labels=c("Transmission Alone","Transmission +\nCommunication")) + 
  scale_color_discrete("Condition", breaks = c("t","c"), labels = c("Transmission Alone", "Transmission +\nCommunication")) +
  geom_hline(yintercept=9.95, linetype = 3) + geom_hline(yintercept=5.95, linetype = 4) + 
  annotate("text", x = 0.6, y = 10.6, size = 4, label="C") + 
  annotate("text", x = 0.6, y = 6.6, size = 4, label = "I") +
  theme(axis.text=axistext, axis.title.x = xaxistitle, axis.title.y=yaxistitle, legend.key.width = unit(1, "cm")) +
  geom_point(data = exp2_spec_descriptives, aes(x = group2, y = mean, color = group1), size = 2) +
  geom_line(data = exp2_spec_descriptives, aes(x = group2, y = mean, color = group1, group = group1, linetype = group1), size = 1) +
  geom_errorbar(data = exp2_spec_descriptives, aes(x = group2, group = group1, color = group1, y = mean, ymin = Lowlim, ymax = Uplim), width = 0.25, size = 1, position = dodge, show.legend = FALSE)
ggsave(filename="Exp2Specificity.pdf",width=7.25,height=5.5)

# Statistical analysis

# Generation as ordered factor

exp2spec$Generation <- ordered(exp2spec$Generation)

exp2_spec_stat <- aov(Specificity ~ Condition * Generation, exp2spec)
summary(exp2_spec_stat, split=list(Generation = list("Linear trend"=1)))

# Comparison of generation 5 of Transmission Alone in Experiment 2 with Individuals from Experiment 1

exp2_spec_t_g5 <- subset(exp2spec, Condition == "t")
exp2_spec_t_g5 <- subset(exp2_spec_t_g5, Generation == 5)
exp2_spec_t_g5 <- exp2_spec_t_g5[, -2]

exp1_spec_i <- subset(exp1spec, Condition == "i")

spec_comparison <- rbind(exp2_spec_t_g5, exp1_spec_i)

spec_comparison_stat <- t.test(spec_comparison$Specificity ~ spec_comparison$Condition)
print(spec_comparison_stat)

# Convexity

# read in data

exp2conv <- read.delim("output/experiment_2_convexity.txt", header = TRUE, sep = "\t")

tmiss <- subset(exp2conv, Condition == "t")[c(1, 2, 6)]
comm <- subset(exp2conv, Condition == "c")[c(1, 2, 6)]

# average communicative pairs
# make vector of Generation to add back
gen_vector = rep(c(1, 2, 3, 4, 5),8)

comm_avs <- by(comm$Corrected, gl(ceiling(length(comm$Corrected)/2), 2, length(comm$Corrected)), mean)
comm_avs <- as.list(comm_avs)
comm_avs <- data.frame(Corrected = do.call("rbind", comm_avs))

exp2conv <- rbind(tmiss, data.frame(Condition = "c", Generation = gen_vector, Corrected = comm_avs$Corrected))

# reorder factor levels

exp2conv$Condition = factor(exp2conv$Condition,levels(exp2conv$Condition)[c(2,1)])

# Confidence intervals

exp2_conv_descriptives <- describeBy(exp2conv$Corrected, list(exp2conv$Condition, exp2conv$Generation), mat = TRUE)

# reorder factor levels

exp2_conv_descriptives$group1 = factor(exp2_conv_descriptives$group1,levels(exp2_conv_descriptives$group1)[c(2,1)])

# add confidence intervals

exp2_conv_t_g1_ci <- conf_ints_within(exp2_conv_descriptives[1, 6], idf, exp2_conv_descriptives[1, 16])
exp2_conv_c_g1_ci <- conf_ints_within(exp2_conv_descriptives[2, 6], cdf, exp2_conv_descriptives[2, 16])

print(exp2_conv_t_g1_ci)
print(exp2_conv_c_g1_ci)

# between conditions in generation 1

exp2_conv_g1_between_ci <- conf_ints_between(m1 = exp2_conv_descriptives[1,6], m2 = exp2_conv_descriptives[2,6], sd1 = exp2_conv_descriptives[1,7],
                                             sd2 = exp2_conv_descriptives[2,7], n1 = exp2_conv_descriptives[1,5], n2 = exp2_conv_descriptives[2,5],
                                             method = "WS")

print(exp2_conv_g1_between_ci)

# calculate rest of confidence intervals

exp2_conv_t_g2_ci <- conf_ints_within(exp2_conv_descriptives[3, 6], idf, exp2_conv_descriptives[3, 16])
exp2_conv_c_g2_ci <- conf_ints_within(exp2_conv_descriptives[4, 6], idf, exp2_conv_descriptives[4, 16])
exp2_conv_t_g3_ci <- conf_ints_within(exp2_conv_descriptives[5, 6], idf, exp2_conv_descriptives[5, 16])
exp2_conv_c_g3_ci <- conf_ints_within(exp2_conv_descriptives[6, 6], idf, exp2_conv_descriptives[6, 16])
exp2_conv_t_g4_ci <- conf_ints_within(exp2_conv_descriptives[7, 6], idf, exp2_conv_descriptives[7, 16])
exp2_conv_c_g4_ci <- conf_ints_within(exp2_conv_descriptives[8, 6], idf, exp2_conv_descriptives[8, 16])

# generation 5

exp2_conv_t_g5_ci <- conf_ints_within(exp2_conv_descriptives[9, 6], idf, exp2_conv_descriptives[9, 16])
exp2_conv_c_g5_ci <- conf_ints_within(exp2_conv_descriptives[10, 6], cdf, exp2_conv_descriptives[10, 16])

print(exp2_conv_t_g5_ci)
print(exp2_conv_c_g5_ci)

# difference from generation 1 to 5 in transmission condition

exp2_conv_t_between_ci <- conf_ints_between(m1 = exp2_conv_descriptives[1,6], m2 = exp2_conv_descriptives[9,6], sd1 = exp2_conv_descriptives[1,7],
                                            sd2 = exp2_conv_descriptives[9,7], n1 = exp2_conv_descriptives[1,5], n2 = exp2_conv_descriptives[9,5],
                                            method = "WS")

print(exp2_conv_t_between_ci)

# difference from generation 1 to 5 in communication condition

exp2_conv_c_between_ci <- conf_ints_between(m1 = exp2_conv_descriptives[2,6], m2 = exp2_conv_descriptives[10,6], sd1 = exp2_conv_descriptives[2,7],
                                            sd2 = exp2_conv_descriptives[10,7], n1 = exp2_conv_descriptives[2,5], n2 = exp2_conv_descriptives[10,5],
                                            method = "WS")

print(exp2_conv_c_between_ci)

# comparison of final number in transmission condition in experiment 2 with individuals from experiment 1

exp2_conv_c_between_expts_ci_1 <- conf_ints_between(m1 = exp1_conv_descriptives[1,5], m2 = exp2_conv_descriptives[9,6], sd1 = exp1_conv_descriptives[1,6],
                                                    sd2 = exp2_conv_descriptives[9,7], n1 = exp1_conv_descriptives[1,4], n2 = exp2_conv_descriptives[9,5],
                                                    method = "WS")

print(exp2_conv_c_between_expts_ci_1)

# comparison of final number in communication condition in experiment 2 with communicators from experiment 1

exp2_conv_c_between_expts_ci_2 <- conf_ints_between(m1 = exp1_conv_descriptives[2,5], m2 = exp2_conv_descriptives[10,6], sd1 = exp1_conv_descriptives[2,6],
                                                    sd2 = exp2_conv_descriptives[10,7], n1 = exp1_conv_descriptives[2,4], n2 = exp2_conv_descriptives[10,5],
                                                    method = "WS")

print(exp2_conv_c_between_expts_ci_2)

# add all these to data frame

exp2_conv_descriptives["Lowlim"] <- c(exp2_conv_t_g1_ci$Lowlim, exp2_conv_c_g1_ci$Lowlim, 
                                      exp2_conv_t_g2_ci$Lowlim, exp2_conv_c_g2_ci$Lowlim, 
                                      exp2_conv_t_g3_ci$Lowlim, exp2_conv_c_g3_ci$Lowlim, 
                                      exp2_conv_t_g4_ci$Lowlim, exp2_conv_c_g4_ci$Lowlim, 
                                      exp2_conv_t_g5_ci$Lowlim, exp2_conv_c_g5_ci$Lowlim)
exp2_conv_descriptives["Uplim"] <- c(exp2_conv_t_g1_ci$Uplim, exp2_conv_c_g1_ci$Uplim, 
                                     exp2_conv_t_g2_ci$Uplim, exp2_conv_c_g2_ci$Uplim, 
                                     exp2_conv_t_g3_ci$Uplim, exp2_conv_c_g3_ci$Uplim, 
                                     exp2_conv_t_g4_ci$Uplim, exp2_conv_c_g4_ci$Uplim, 
                                     exp2_conv_t_g5_ci$Uplim, exp2_conv_c_g5_ci$Uplim)



# Graph

# average transmission pairs as well for clarity

comm <- subset(exp2conv, Condition == "c")
tmiss <- subset(exp2conv, Condition == "t")

tmiss_avs <- by(tmiss$Corrected, gl(ceiling(length(tmiss$Corrected)/2), 2, length(tmiss$Corrected)), mean)
tmiss_avs <- as.list(tmiss_avs)
tmiss_avs <- data.frame(Corrected = do.call("rbind", tmiss_avs))

exp2conv_plot <- rbind(data.frame(Condition = "t", Generation = gen_vector, Corrected = tmiss_avs$Corrected), comm)


# add Chain back to data frame for grouping raw data

exp2conv_plot$Chain <- chain_vector

exp2_conv_graph <- ggplot(exp2conv_plot, aes(x=Generation, y=Corrected))
exp2_conv_graph + theme_bw() + geom_line(aes(linetype = Condition, color = Condition, group=interaction(Chain, Condition)), alpha = 0.3, show.legend = FALSE) + 
  scale_x_discrete("\nGeneration") + scale_y_continuous('Convexity\n', limits=c(-0.1,1)) + 
  scale_linetype_discrete("Condition",breaks=c("t","c"),labels=c("Transmission Alone","Transmission +\nCommunication")) + 
  scale_color_discrete("Condition", breaks = c("t","c"), labels=c("Transmission Alone", "Transmission +\nCommunication")) +
  geom_hline(yintercept=0.57, linetype = 3) + geom_hline(yintercept=0.65, linetype = 4) + 
  annotate("text", x = 0.6, y = 0.6, size = 4, label="C") + 
  annotate("text", x = 0.6, y = 0.68, size = 4, label = "I") +
  theme(axis.text=axistext, axis.title.x = xaxistitle, axis.title.y=yaxistitle, legend.key.width = unit(1, "cm")) +
  geom_point(data = exp2_conv_descriptives, aes(x = group2, y = mean, color = group1), size = 2) +
  geom_line(data = exp2_conv_descriptives, aes(x = group2, y = mean, color = group1, group = group1, linetype = group1), size = 1) +
  geom_errorbar(data = exp2_conv_descriptives, aes(x = group2, group = group1, y = mean, color = group1, ymin = Lowlim, ymax = Uplim), width = 0.25, size = 1, position = dodge, show.legend = FALSE)
ggsave(filename="Exp2Convexity.pdf",width=7.25,height=5.5)


# Statistical analysis

# Generation as ordered factor

exp2conv$Generation <- ordered(exp2conv$Generation)

exp2_conv_stat <- aov(Corrected ~ Condition * Generation, exp2conv)
summary(exp2_conv_stat, split=list(Generation = list("Linear trend"=1)))

# Comparison of generation 5 of Transmission Alone in Experiment 2 with Individuals from Experiment 1

exp2_conv_t_g5 <- subset(exp2conv, Condition == "t")
exp2_conv_t_g5 <- subset(exp2_conv_t_g5, Generation == 5)
exp2_conv_t_g5 <- exp2_conv_t_g5[, -2]

exp1_conv_i <- subset(exp1conv, Condition == "i")

conv_comparison <- rbind(exp2_conv_t_g5, exp1_conv_i)

conv_comparison_stat <- t.test(conv_comparison$Corrected ~ conv_comparison$Condition)
print(conv_comparison_stat)


# Alignment

# for alignment and communicative success, degrees of freedom are 8-1 = 7 for both conditions
idf = 7
cdf = 7

# read in data

exp2align <- read.delim("output/experiment_2_alignment.txt", header = TRUE, sep = "\t")

# reorder factor levels

exp2align$Condition = factor(exp2align$Condition,levels(exp2align$Condition)[c(2,1)])

# Confidence intervals

exp2_align_descriptives <- describeBy(exp2align$AdjustedRandIndex, list(exp2align$Condition, exp2align$Generation), mat = TRUE)

# reorder factor levels

exp2_align_descriptives$group1 = factor(exp2_align_descriptives$group1,levels(exp2_align_descriptives$group1)[c(2,1)])

# add confidence intervals

exp2_align_t_g1_ci <- conf_ints_within(exp2_align_descriptives[1, 6], idf, exp2_align_descriptives[1, 16])
exp2_align_c_g1_ci <- conf_ints_within(exp2_align_descriptives[2, 6], cdf, exp2_align_descriptives[2, 16])

print(exp2_align_t_g1_ci)
print(exp2_align_c_g1_ci)

# between conditions in generation 1

exp2_align_g1_between_ci <- conf_ints_between(m1 = exp2_align_descriptives[1,6], m2 = exp2_align_descriptives[2,6], sd1 = exp2_align_descriptives[1,7],
                                             sd2 = exp2_align_descriptives[2,7], n1 = exp2_align_descriptives[1,5], n2 = exp2_align_descriptives[2,5],
                                             method = "standard")

print(exp2_align_g1_between_ci)

# calculate rest of confidence intervals

exp2_align_t_g2_ci <- conf_ints_within(exp2_align_descriptives[3, 6], idf, exp2_align_descriptives[3, 16])
exp2_align_c_g2_ci <- conf_ints_within(exp2_align_descriptives[4, 6], idf, exp2_align_descriptives[4, 16])
exp2_align_t_g3_ci <- conf_ints_within(exp2_align_descriptives[5, 6], idf, exp2_align_descriptives[5, 16])
exp2_align_c_g3_ci <- conf_ints_within(exp2_align_descriptives[6, 6], idf, exp2_align_descriptives[6, 16])
exp2_align_t_g4_ci <- conf_ints_within(exp2_align_descriptives[7, 6], idf, exp2_align_descriptives[7, 16])
exp2_align_c_g4_ci <- conf_ints_within(exp2_align_descriptives[8, 6], idf, exp2_align_descriptives[8, 16])

# generation 5

exp2_align_t_g5_ci <- conf_ints_within(exp2_align_descriptives[9, 6], idf, exp2_align_descriptives[9, 16])
exp2_align_c_g5_ci <- conf_ints_within(exp2_align_descriptives[10, 6], cdf, exp2_align_descriptives[10, 16])

print(exp2_align_t_g5_ci)
print(exp2_align_c_g5_ci)

# difference from generation 1 to 5 in transmission condition

exp2_align_t_between_ci <- conf_ints_between(m1 = exp2_align_descriptives[1,6], m2 = exp2_align_descriptives[9,6], sd1 = exp2_align_descriptives[1,7],
                                            sd2 = exp2_align_descriptives[9,7], n1 = exp2_align_descriptives[1,5], n2 = exp2_align_descriptives[9,5],
                                            method = "WS")

print(exp2_align_t_between_ci)

# difference from generation 1 to 5 in communication condition

exp2_align_c_between_ci <- conf_ints_between(m1 = exp2_align_descriptives[2,6], m2 = exp2_align_descriptives[10,6], sd1 = exp2_align_descriptives[2,7],
                                            sd2 = exp2_align_descriptives[10,7], n1 = exp2_align_descriptives[2,5], n2 = exp2_align_descriptives[10,5],
                                            method = "WS")

print(exp2_align_c_between_ci)

# comparison of final number in transmission condition in experiment 2 with individuals from experiment 1

exp2_align_c_between_expts_ci_1 <- conf_ints_between(m1 = exp1_align_descriptives[1,5], m2 = exp2_align_descriptives[9,6], sd1 = exp1_align_descriptives[1,6],
                                                    sd2 = exp2_align_descriptives[9,7], n1 = exp1_align_descriptives[1,4], n2 = exp2_align_descriptives[9,5],
                                                    method = "WS")

print(exp2_align_c_between_expts_ci_1)

# comparison of final number in communication condition in experiment 2 with communicators from experiment 1

exp2_align_c_between_expts_ci_2 <- conf_ints_between(m1 = exp1_align_descriptives[2,5], m2 = exp2_align_descriptives[10,6], sd1 = exp1_align_descriptives[2,6],
                                                    sd2 = exp2_align_descriptives[10,7], n1 = exp1_align_descriptives[2,4], n2 = exp2_align_descriptives[10,5],
                                                    method = "WS")

print(exp2_align_c_between_expts_ci_2)

# add all these to data frame

exp2_align_descriptives["Lowlim"] <- c(exp2_align_t_g1_ci$Lowlim, exp2_align_c_g1_ci$Lowlim, 
                                      exp2_align_t_g2_ci$Lowlim, exp2_align_c_g2_ci$Lowlim, 
                                      exp2_align_t_g3_ci$Lowlim, exp2_align_c_g3_ci$Lowlim, 
                                      exp2_align_t_g4_ci$Lowlim, exp2_align_c_g4_ci$Lowlim, 
                                      exp2_align_t_g5_ci$Lowlim, exp2_align_c_g5_ci$Lowlim)
exp2_align_descriptives["Uplim"] <- c(exp2_align_t_g1_ci$Uplim, exp2_align_c_g1_ci$Uplim, 
                                     exp2_align_t_g2_ci$Uplim, exp2_align_c_g2_ci$Uplim, 
                                     exp2_align_t_g3_ci$Uplim, exp2_align_c_g3_ci$Uplim, 
                                     exp2_align_t_g4_ci$Uplim, exp2_align_c_g4_ci$Uplim, 
                                     exp2_align_t_g5_ci$Uplim, exp2_align_c_g5_ci$Uplim)



# Graph

# add Chain to data frame for grouping raw data

exp2align_plot <- exp2align
exp2align_plot$Chain <- chain_vector

exp2_align_graph <- ggplot(exp2align_plot, aes(x=Generation, y=AdjustedRandIndex))
exp2_align_graph + theme_bw() + geom_line(aes(linetype = Condition, color = Condition, group=interaction(Chain, Condition)), alpha = 0.3) + 
  scale_x_discrete("\nGeneration") + scale_y_continuous('Alignment (Adjusted Rand index)\n', limits=c(-0.05,1)) + 
  scale_linetype_discrete("Condition",breaks=c("t","c"),labels=c("Transmission Alone","Transmission +\nCommunication")) + 
  scale_color_discrete("Condition", breaks=c("t","c",labels=c("Transmission Alone", "Transmission +\nCommunication"))) +
  geom_hline(yintercept=0.24, linetype = 3) + geom_hline(yintercept=0.33, linetype = 4) + 
  annotate("text", x = 0.6, y = 0.27, size = 4, label="C") + 
  annotate("text", x = 0.6, y = 0.36, size = 4, label = "I") + 
  theme(axis.text=axistext, axis.title.x = xaxistitle, axis.title.y=yaxistitle, legend.position = "none") +
  geom_point(data = exp2_align_descriptives, aes(x = group2, y = mean, color = group1), size = 2) +
  geom_line(data = exp2_align_descriptives, aes(x = group2, y = mean, group = group1, color = group1, linetype = group1), size = 1) +
  geom_errorbar(data = exp2_align_descriptives, aes(x = group2, group = group1, color = group1, y = mean, ymin = Lowlim, ymax = Uplim), width = 0.25, size = 1, position = dodge)
ggsave(filename="Exp2Alignment.pdf",width=7.25,height=5.5)


# Statistical analysis

# Generation as ordered factor

exp2align$Generation <- ordered(exp2align$Generation)

exp2_align_stat <- aov(AdjustedRandIndex ~ Condition * Generation, exp2align)
summary(exp2_align_stat, split=list(Generation = list("Linear trend"=1)))

# Comparison of generation 5 of Transmission Alone in Experiment 2 with Individuals from Experiment 1

exp2_align_t_g5 <- subset(exp2align, Condition == "t")
exp2_align_t_g5 <- subset(exp2_align_t_g5, Generation == 5)
exp2_align_t_g5 <- exp2_align_t_g5[, -2]

exp1_align_i <- subset(exp1align, Condition == "i")

align_comparison <- rbind(exp2_align_t_g5, exp1_align_i)

align_comparison_stat <- t.test(align_comparison$AdjustedRandIndex ~ align_comparison$Condition)
print(align_comparison_stat)



# Convergence

# Here, confidence intervals are calculated via a Monte Carlo process in the Python code

# read in data

exp2converge <- read.delim("output/experiment_2_convergence.txt", header = TRUE, sep = "\t")

print(exp2converge)

# reorder factor levels

exp2converge$Condition = factor(exp2converge$Condition,levels(exp2converge$Condition)[c(2,1)])

exp2_converge_graph <- ggplot(exp2converge, aes(x=Generation, y=Convergence, group=Condition))
exp2_converge_graph + theme_bw() + geom_point(aes(color = Condition), size = 2) + 
  geom_line(aes(linetype=Condition, color=Condition), size = 1) + 
  geom_errorbar(aes(color = Condition, ymin=LowLim, ymax=UpLim, width=0.25),position=dodge, size = 1, show.legend = FALSE) + 
  scale_x_continuous("\nGeneration") + scale_y_continuous('', limits=c(-0.05,1)) + 
  scale_linetype_discrete("Condition",breaks=c("t","c"),labels=c("Transmission Alone","Transmission +\nCommunication")) + 
  scale_color_discrete("Condition",breaks=c("t","c"),labels=c("Transmission Alone", "Transmission +\nCommunication")) +
  geom_hline(yintercept=0.18, linetype = 3) + geom_hline(yintercept=0.36, linetype = 4) + 
  annotate("text", x = 0.6, y = 0.21, size = 4, label="C") + 
  annotate("text", x = 0.6, y = 0.39, size = 4, label = "I") + 
  theme(axis.text=axistext, axis.title.x = xaxistitle, axis.title.y=yaxistitle, legend.position = c(0.8, 0.8), legend.title = element_text(size=14, face = "bold"), legend.text = element_text(size=12), legend.key.width = unit(1, "cm"))
ggsave(filename="Exp2Convergence.pdf",width=7.25,height=5.5)


# Communicative success (veridical and simulated)

# read in data

exp2success <- read.delim("output/experiment_2_success_last_2.txt", header = TRUE, sep = "\t")

exp2simsuccess <- read.delim("output/experiment_2_sim_success.txt", header = TRUE, sep = "\t")

# combine these files

exp2success["Condition"] <- "c"
exp2simsuccess["Condition"] <- "t"

exp2success <- rbind(data.frame(Condition = exp2simsuccess$Condition, Generation = exp2simsuccess$Generation,
                                SuccessRaw = exp2simsuccess$SimSuccessRaw, SuccessCorr = exp2simsuccess$SimSuccessCorr), 
                     exp2success)

# Confidence intervals

exp2_success_descriptives <- describeBy(exp2success$SuccessRaw, list(exp2success$Condition, exp2success$Generation), mat = TRUE)

# reorder factor levels

exp2_success_descriptives$group1 = factor(exp2_success_descriptives$group1,levels(exp2_success_descriptives$group1)[c(2,1)])

# add confidence intervals

exp2_success_t_g1_ci <- conf_ints_within(exp2_success_descriptives[1, 6], idf, exp2_success_descriptives[1, 16])
exp2_success_c_g1_ci <- conf_ints_within(exp2_success_descriptives[2, 6], cdf, exp2_success_descriptives[2, 16])

print(exp2_success_t_g1_ci)
print(exp2_success_c_g1_ci)

# between conditions in generation 1

exp2_success_g1_between_ci <- conf_ints_between(m1 = exp2_success_descriptives[1,6], m2 = exp2_success_descriptives[2,6], sd1 = exp2_success_descriptives[1,7],
                                              sd2 = exp2_success_descriptives[2,7], n1 = exp2_success_descriptives[1,5], n2 = exp2_success_descriptives[2,5],
                                              method = "WS")

print(exp2_success_g1_between_ci)

# calculate rest of confidence intervals

exp2_success_t_g2_ci <- conf_ints_within(exp2_success_descriptives[3, 6], idf, exp2_success_descriptives[3, 16])
exp2_success_c_g2_ci <- conf_ints_within(exp2_success_descriptives[4, 6], idf, exp2_success_descriptives[4, 16])
exp2_success_t_g3_ci <- conf_ints_within(exp2_success_descriptives[5, 6], idf, exp2_success_descriptives[5, 16])
exp2_success_c_g3_ci <- conf_ints_within(exp2_success_descriptives[6, 6], idf, exp2_success_descriptives[6, 16])
exp2_success_t_g4_ci <- conf_ints_within(exp2_success_descriptives[7, 6], idf, exp2_success_descriptives[7, 16])
exp2_success_c_g4_ci <- conf_ints_within(exp2_success_descriptives[8, 6], idf, exp2_success_descriptives[8, 16])

# generation 5

exp2_success_t_g5_ci <- conf_ints_within(exp2_success_descriptives[9, 6], idf, exp2_success_descriptives[9, 16])
exp2_success_c_g5_ci <- conf_ints_within(exp2_success_descriptives[10, 6], cdf, exp2_success_descriptives[10, 16])

print(exp2_success_t_g5_ci)
print(exp2_success_c_g5_ci)

# difference from generation 1 to 5 in transmission condition

exp2_success_t_between_ci <- conf_ints_between(m1 = exp2_success_descriptives[1,6], m2 = exp2_success_descriptives[9,6], sd1 = exp2_success_descriptives[1,7],
                                             sd2 = exp2_success_descriptives[9,7], n1 = exp2_success_descriptives[1,5], n2 = exp2_success_descriptives[9,5],
                                             method = "WS")

print(exp2_success_t_between_ci)

# difference from generation 1 to 5 in communication condition

exp2_success_c_between_ci <- conf_ints_between(m1 = exp2_success_descriptives[2,6], m2 = exp2_success_descriptives[10,6], sd1 = exp2_success_descriptives[2,7],
                                             sd2 = exp2_success_descriptives[10,7], n1 = exp2_success_descriptives[2,5], n2 = exp2_success_descriptives[10,5],
                                             method = "WS")

print(exp2_success_c_between_ci)

# comparison of final number in communication condition in experiment 2 with communicators from experiment 1
# we need to divide success in the last 2 rounds in experiment 1 by 2 first, to get average for comparison
exp1success["AverageSuccess"] <- exp1success$Success/2

exp1_success_descriptives <- describe(exp1success$AverageSuccess)

exp2_success_c_between_expts_ci <- conf_ints_between(m1 = exp1_success_descriptives[1,3], m2 = exp2_success_descriptives[10,6], sd1 = exp1_success_descriptives[1,4],
                                                     sd2 = exp2_success_descriptives[10,7], n1 = exp1_success_descriptives[1,2], n2 = exp2_success_descriptives[10,5],
                                                     method = "WS")

print(exp2_success_c_between_expts_ci)

# add all these to data frame

exp2_success_descriptives["Lowlim"] <- c(exp2_success_t_g1_ci$Lowlim, exp2_success_c_g1_ci$Lowlim, 
                                       exp2_success_t_g2_ci$Lowlim, exp2_success_c_g2_ci$Lowlim, 
                                       exp2_success_t_g3_ci$Lowlim, exp2_success_c_g3_ci$Lowlim, 
                                       exp2_success_t_g4_ci$Lowlim, exp2_success_c_g4_ci$Lowlim, 
                                       exp2_success_t_g5_ci$Lowlim, exp2_success_c_g5_ci$Lowlim)
exp2_success_descriptives["Uplim"] <- c(exp2_success_t_g1_ci$Uplim, exp2_success_c_g1_ci$Uplim, 
                                      exp2_success_t_g2_ci$Uplim, exp2_success_c_g2_ci$Uplim, 
                                      exp2_success_t_g3_ci$Uplim, exp2_success_c_g3_ci$Uplim, 
                                      exp2_success_t_g4_ci$Uplim, exp2_success_c_g4_ci$Uplim, 
                                      exp2_success_t_g5_ci$Uplim, exp2_success_c_g5_ci$Uplim)

# add column designating these as Overall scores
exp2_success_descriptives["Measure"] <- "Overall"

# summarise per-category scores

exp2_success_corr_descriptives <- describeBy(exp2success$SuccessCorr, list(exp2success$Condition, exp2success$Generation), mat = TRUE)

# reorder factor levels

exp2_success_corr_descriptives$group1 = factor(exp2_success_corr_descriptives$group1,levels(exp2_success_corr_descriptives$group1)[c(2,1)])

# calculate confidence intervals for per-category scores

exp2_success_corr_t_g1_ci <- conf_ints_within(exp2_success_corr_descriptives[1, 6], idf, exp2_success_corr_descriptives[1, 16])
exp2_success_corr_c_g1_ci <- conf_ints_within(exp2_success_corr_descriptives[2, 6], cdf, exp2_success_corr_descriptives[2, 16])
exp2_success_corr_t_g2_ci <- conf_ints_within(exp2_success_corr_descriptives[3, 6], idf, exp2_success_corr_descriptives[3, 16])
exp2_success_corr_c_g2_ci <- conf_ints_within(exp2_success_corr_descriptives[4, 6], idf, exp2_success_corr_descriptives[4, 16])
exp2_success_corr_t_g3_ci <- conf_ints_within(exp2_success_corr_descriptives[5, 6], idf, exp2_success_corr_descriptives[5, 16])
exp2_success_corr_c_g3_ci <- conf_ints_within(exp2_success_corr_descriptives[6, 6], idf, exp2_success_corr_descriptives[6, 16])
exp2_success_corr_t_g4_ci <- conf_ints_within(exp2_success_corr_descriptives[7, 6], idf, exp2_success_corr_descriptives[7, 16])
exp2_success_corr_c_g4_ci <- conf_ints_within(exp2_success_corr_descriptives[8, 6], idf, exp2_success_corr_descriptives[8, 16])
exp2_success_corr_t_g5_ci <- conf_ints_within(exp2_success_corr_descriptives[9, 6], idf, exp2_success_corr_descriptives[9, 16])
exp2_success_corr_c_g5_ci <- conf_ints_within(exp2_success_corr_descriptives[10, 6], cdf, exp2_success_corr_descriptives[10, 16])

# add all these to data frame

exp2_success_corr_descriptives["Lowlim"] <- c(exp2_success_corr_t_g1_ci$Lowlim, exp2_success_corr_c_g1_ci$Lowlim, 
                                         exp2_success_corr_t_g2_ci$Lowlim, exp2_success_corr_c_g2_ci$Lowlim, 
                                         exp2_success_corr_t_g3_ci$Lowlim, exp2_success_corr_c_g3_ci$Lowlim, 
                                         exp2_success_corr_t_g4_ci$Lowlim, exp2_success_corr_c_g4_ci$Lowlim, 
                                         exp2_success_corr_t_g5_ci$Lowlim, exp2_success_corr_c_g5_ci$Lowlim)
exp2_success_corr_descriptives["Uplim"] <- c(exp2_success_corr_t_g1_ci$Uplim, exp2_success_corr_c_g1_ci$Uplim, 
                                        exp2_success_corr_t_g2_ci$Uplim, exp2_success_corr_c_g2_ci$Uplim, 
                                        exp2_success_corr_t_g3_ci$Uplim, exp2_success_corr_c_g3_ci$Uplim, 
                                        exp2_success_corr_t_g4_ci$Uplim, exp2_success_corr_c_g4_ci$Uplim, 
                                        exp2_success_corr_t_g5_ci$Uplim, exp2_success_corr_c_g5_ci$Uplim)

# add column designating these as per-category scores
exp2_success_corr_descriptives["Measure"] <- "Per-category"

# make combined data frame with per-category and overall scores

exp2_success_descriptives <- rbind(exp2_success_descriptives, exp2_success_corr_descriptives)

# Graph

# restructure raw data to long format

exp2success_raw <- subset(exp2success, select = c(Condition, Generation, SuccessRaw))
exp2success_corr <- subset(exp2success, select = c(Condition, Generation, SuccessCorr))

names(exp2success_raw)[3] <- "Success"
names(exp2success_corr)[3] <- "Success"

exp2success_raw$Measure <- "Overall"
exp2success_corr$Measure <- "Per-category"

exp2success_plot <- rbind(exp2success_raw, exp2success_corr)

# add Chain back to data frame - different ordering in this data frame

chain_vector_success <- rep(c(1,2,3,4,5,6,7,8),20)

exp2success_plot$Chain <- chain_vector_success

# reference lines for each facet

reflines <- data.frame(Measure = c("Overall", "Per-category"), Z = c(293.75, 34.96116493))

exp2_success_graph <- ggplot(exp2success_plot, aes(x=Generation, y=Success))
exp2_success_graph + theme_bw() + geom_line(aes(linetype = Condition, color = Condition, group=interaction(Chain, Condition)), alpha = 0.3, show.legend = FALSE) + 
  scale_x_discrete("\nGeneration") + scale_y_continuous('Communicative success\n') + 
  scale_linetype_discrete("Condition",breaks=c("t","c"),labels=c("Transmission Alone","Transmission +\nCommunication")) + 
  scale_color_discrete("Condition",breaks=c("t","c"),labels=c("Transmission Alone", "Transmission +\nCommunication")) +
  geom_hline(data = reflines, linetype = 3, aes(yintercept = Z)) +
  theme(axis.text=axistext, axis.title.x = xaxistitle, axis.title.y=yaxistitle, legend.key.width = unit(1, "cm")) +
  geom_point(data = exp2_success_descriptives, aes(x = group2, y = mean, color = group1), size = 2) +
  geom_line(data = exp2_success_descriptives, aes(x = group2, y = mean, group = group1, color = group1, linetype = group1), size = 1) +
  geom_errorbar(data = exp2_success_descriptives, aes(x = group2, group = group1, color = group1, y = mean, ymin = Lowlim, ymax = Uplim), width = 0.25, size = 1, position = dodge, show.legend = FALSE) +
  facet_grid(Measure~., scales="free")
ggsave(filename="Exp2Success.pdf",width=7.25,height=5.5)


# Statistical analysis

# Generation as ordered factor

exp2success$Generation <- ordered(exp2success$Generation)

exp2_success_stat <- aov(SuccessRaw ~ Condition * Generation, exp2success)
summary(exp2_success_stat, split=list(Generation = list("Linear trend"=1)))


# Learnability

# for learnability, degrees of freedom are 16-1 = 15 for transmission-alone, 8-1 = 7 for transmission + communication
idf = 15
cdf = 7


# read in data

exp2learn <- read.delim("output/experiment_2_learnability.txt", header = TRUE, sep = "\t")

tmiss <- subset(exp2learn, Condition == "t")
comm <- subset(exp2learn, Condition == "c")

# average communicative pairs
# make vector of Generation to add back - this time no generation 1 (learnability undefined), 
# order also different because of how the Python code calculates this

gen_vector = c(rep(2,8), rep(3,8), rep(4,8), rep(5,8))

comm_avs <- by(comm$Learnability, gl(ceiling(length(comm$Learnability)/2), 2, length(comm$Learnability)), mean)
comm_avs <- as.list(comm_avs)
comm_avs <- data.frame(Learnability = do.call("rbind", comm_avs))

exp2learn <- rbind(tmiss, data.frame(Condition = "c", Generation = gen_vector, Learnability = comm_avs$Learnability))

# reorder factor levels

exp2learn$Condition = factor(exp2learn$Condition,levels(exp2learn$Condition)[c(2,1)])

# Confidence intervals

exp2_learn_descriptives <- describeBy(exp2learn$Learnability, list(exp2learn$Condition, exp2learn$Generation), mat = TRUE)

# reorder factor levels

exp2_learn_descriptives$group1 = factor(exp2_learn_descriptives$group1,levels(exp2_learn_descriptives$group1)[c(2,1)])

# add confidence intervals

exp2_learn_t_g2_ci <- conf_ints_within(exp2_learn_descriptives[1, 6], idf, exp2_learn_descriptives[1, 16])
exp2_learn_c_g2_ci <- conf_ints_within(exp2_learn_descriptives[2, 6], cdf, exp2_learn_descriptives[2, 16])

print(exp2_learn_t_g2_ci)
print(exp2_learn_c_g2_ci)

# between conditions in generation 2

exp2_learn_g2_between_ci <- conf_ints_between(m1 = exp2_learn_descriptives[1,6], m2 = exp2_learn_descriptives[2,6], sd1 = exp2_learn_descriptives[1,7],
                                              sd2 = exp2_learn_descriptives[2,7], n1 = exp2_learn_descriptives[1,5], n2 = exp2_learn_descriptives[2,5],
                                              method = "WS")

print(exp2_learn_g2_between_ci)

# calculate rest of confidence intervals

exp2_learn_t_g3_ci <- conf_ints_within(exp2_learn_descriptives[3, 6], idf, exp2_learn_descriptives[3, 16])
exp2_learn_c_g3_ci <- conf_ints_within(exp2_learn_descriptives[4, 6], idf, exp2_learn_descriptives[4, 16])
exp2_learn_t_g4_ci <- conf_ints_within(exp2_learn_descriptives[5, 6], idf, exp2_learn_descriptives[5, 16])
exp2_learn_c_g4_ci <- conf_ints_within(exp2_learn_descriptives[6, 6], idf, exp2_learn_descriptives[6, 16])

# generation 5

exp2_learn_t_g5_ci <- conf_ints_within(exp2_learn_descriptives[7, 6], idf, exp2_learn_descriptives[7, 16])
exp2_learn_c_g5_ci <- conf_ints_within(exp2_learn_descriptives[8, 6], idf, exp2_learn_descriptives[8, 16])

print(exp2_learn_t_g5_ci)
print(exp2_learn_c_g5_ci)

# difference from generation 2 to 5 in transmission condition

exp2_learn_t_between_ci <- conf_ints_between(m1 = exp2_learn_descriptives[1,6], m2 = exp2_learn_descriptives[7,6], sd1 = exp2_learn_descriptives[1,7],
                                             sd2 = exp2_learn_descriptives[7,7], n1 = exp2_learn_descriptives[1,5], n2 = exp2_learn_descriptives[7,5],
                                             method = "WS")

print(exp2_learn_t_between_ci)

# difference from generation 2 to 5 in communication condition

exp2_learn_c_between_ci <- conf_ints_between(m1 = exp2_learn_descriptives[2,6], m2 = exp2_learn_descriptives[8,6], sd1 = exp2_learn_descriptives[2,7],
                                             sd2 = exp2_learn_descriptives[8,7], n1 = exp2_learn_descriptives[2,5], n2 = exp2_learn_descriptives[8,5],
                                             method = "standard")

print(exp2_learn_c_between_ci)

# add all these to data frame

exp2_learn_descriptives["Lowlim"] <- c(exp2_learn_t_g2_ci$Lowlim, exp2_learn_c_g2_ci$Lowlim, 
                                       exp2_learn_t_g3_ci$Lowlim, exp2_learn_c_g3_ci$Lowlim, 
                                       exp2_learn_t_g4_ci$Lowlim, exp2_learn_c_g4_ci$Lowlim, 
                                       exp2_learn_t_g5_ci$Lowlim, exp2_learn_c_g5_ci$Lowlim)
exp2_learn_descriptives["Uplim"] <- c(exp2_learn_t_g2_ci$Uplim, exp2_learn_c_g2_ci$Uplim, 
                                      exp2_learn_t_g3_ci$Uplim, exp2_learn_c_g3_ci$Uplim, 
                                      exp2_learn_t_g4_ci$Uplim, exp2_learn_c_g4_ci$Uplim, 
                                      exp2_learn_t_g5_ci$Uplim, exp2_learn_c_g5_ci$Uplim)



# Graph

# Generation as ordered factor

exp2learn$Generation <- ordered(exp2learn$Generation)

# average transmission pairs as well for clarity

comm <- subset(exp2learn, Condition == "c")
tmiss <- subset(exp2learn, Condition == "t")

tmiss_avs <- by(tmiss$Learnability, gl(ceiling(length(tmiss$Learnability)/2), 2, length(tmiss$Learnability)), mean)
tmiss_avs <- as.list(tmiss_avs)
tmiss_avs <- data.frame(Learnability = do.call("rbind", tmiss_avs))

exp2learn_plot <- rbind(data.frame(Condition = "t", Generation = gen_vector, Learnability = tmiss_avs$Learnability), comm)


# add Chain back to data frame for grouping raw data

chain_vector_learn <- rep(c(1,2,3,4,5,6,7,8),8)

exp2learn_plot$Chain <- chain_vector_learn

exp2_learn_graph <- ggplot(exp2learn_plot, aes(x=Generation, y=Learnability))
exp2_learn_graph + theme_bw() + geom_line(aes(linetype = Condition, color = Condition, group=interaction(Chain, Condition)), alpha = 0.3, show.legend = FALSE) + 
  scale_x_discrete("\nGeneration") + scale_y_continuous('Category system learnability\n', limits=c(-0.05,1)) + 
  scale_linetype_discrete("Condition",breaks=c("t","c"),labels=c("Transmission Alone","Transmission +\nCommunication")) + 
  scale_color_discrete("Condition",breaks=c("t","c"),labels=c("Transmission Alone","Transmission +\nCommunication")) +
  theme(axis.text=axistext, axis.title.x = xaxistitle, axis.title.y=yaxistitle, legend.key.width = unit(1, "cm")) +
  geom_point(data = exp2_learn_descriptives, aes(x = group2, y = mean, color = group1), size = 2) +
  geom_line(data = exp2_learn_descriptives, aes(x = group2, y = mean, group = group1, color = group1, linetype = group1), size = 1) +
  geom_errorbar(data = exp2_learn_descriptives, aes(x = group2, group = group1, color = group1, y = mean, ymin = Lowlim, ymax = Uplim), width = 0.25, size = 1, position = dodge, show.legend = FALSE)
ggsave(filename="Exp2Learnability.pdf",width=7.25,height=5.5)

# Statistical analysis

exp2_learn_stat <- aov(Learnability ~ Condition * Generation, exp2learn)
summary(exp2_learn_stat, split=list(Generation = list("Linear trend"=1)))

